name: cicd (dev, qa, stage, prod)

on:
  # workflow will be triggered manually
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  eastus-nonprod-deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: eastus-nonprod
    secrets: inherit
    
  eastus-stage-deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: eastus-stage
    secrets: inherit
    
  eastus-prod-deploy:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environment: eastus-prod
    secrets: inherit