name: deploy-infra

on:
  # This is a reusable workflow
  workflow_call:
    inputs:
      environment:
        description: "Name of the environment to deploy"
        required: true
        type: string

permissions:
  # id-token: write
  contents: read

defaults:
  run:
    shell: pwsh
    
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Generate Terraform Plan..."
  terraform-apply:
    needs: terraform-plan
    # set environment to request apporval
    environment: ${{inputs.environment}}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Apply Terraform Plan..."
